### ISSUE TITLE
Sails.js

### ISSUE THREAD

**Issue by ram-you** [xpepermint/express-vue-builder#1]
Hi, I have one question please: can we use-it with an existing **sails.js** project and how?
Thanks.

**Comment by xpepermint** [comment]
It should work because it's only a middleware for express. I don't use Sails so your best option is to check the [example](https://github.com/xpepermint/express-vue-builder/tree/master/example/server). The middleware just register `req.vue` variable which you then use to render your page.

**Comment by ram-you** [comment]
If it was that simple, I would never have asked for your help.

**Comment by xpepermint** [comment]
Hum ... I would love to help but my last Sails project was years ago ... Can you please post a question on stackoverflow and link to this issue? I'm sure this would help others.

**Comment by xpepermint** [comment]
Btw ... why do you need to use Sails.js with Vue.js? I would recommend using this [server-side Vue.js cli template](https://github.com/xpepermint/vue-cli-template) instead. If you need an API, then consider this as a new stand-alone application (e.g. [graphql-example](https://github.com/xpepermint/graphql-example)). You don't wanna mess with monolithic applications in node :).

**Comment by ram-you** [comment]
Thanks for your advice. In fact, I have a great functional project (sails.js + Angular) that I am trying to migrate to Vue.js. Given the complexity of the task, I think I'll follow your advice and start a new project based on the **server-side Vue.js cli template**

**Comment by xpepermint** [comment]
Cool!
